services:
  redis:
    image: redis:6.2.5
    container_name: redis
    environment:
      - REDIS_PASSWORD=admin
    command: [
      "redis-server",
      "--requirepass", "admin",
      "--appendonly", "yes",
      "--maxmemory", "256mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - "6379:6379"

  mongo-chat:
    image: mongo:latest
    container_name: mongo-chat
    hostname: mongo-chat
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chat-db
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo_network
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8888:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo-chat'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - mongo_network
    depends_on:
      - mongo-chat

#   ONLY FOR DEVELOPMENT
  activemq:
    image: symptoma/activemq:5.18.3
    container_name: activemq
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: "false"
      ACTIVEMQ_USERNAME: "myuser"
      ACTIVEMQ_PASSWORD: "mypwd"
      ACTIVEMQ_WEBADMIN_USERNAME: "admin"
      ACTIVEMQ_WEBADMIN_PASSWORD: "admin"


volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge
    name: mongo-network